[world]
name = "Octa Flip"
description = "Octa Flip game on Starknet"
cover_uri = "https://octaflip.com"
icon_uri = "https://octaflip.com"
website = "https://octaflip.com"
seed = "octaflipsepolia1"


[world.socials]
x = "https://octaflip.com"
discord = "https://octaflip.com"
github = "https://octaflip.com"
telegram = "https://octaflip.com"

[namespace]
default = "octa_flip"

[env]
world_address = "0x03657c2945c07d6edb4eb04fa5473d8ac17156c0f78860c78e7f370babf027e2"

[writers]
"octa_flip" = ["octa_flip-actions"]
