[world]
name = "Octa Flip"
description = "Octa Flip game on Starknet"
cover_uri = ""
icon_uri = ""
website = "https://octaflip.com"
seed = "octa_flip_dev_1"


[world.socials]
x = ""
discord = ""
github = ""
telegram = ""

[namespace]
default = "octa_flip"

[env]
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"octa_flip" = ["octa_flip-actions"]
